# Generated by Django 4.2.4 on 2023-09-21 17:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=100)),
                ('E_Mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=60)),
                ('Product_Price', models.IntegerField(default=0)),
                ('Product_Description', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('Product_Image', models.ImageField(upload_to='uploads/products/')),
                ('Category_ID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storeapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('Price', models.IntegerField()),
                ('Date', models.DateField(default=datetime.datetime.today)),
                ('Status', models.BooleanField(default=False)),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.customers')),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.products')),
            ],
        ),
    ]
