# Generated by Django 4.2.4 on 2023-09-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Customer_ID',
        ),
        migrations.AddField(
            model_name='orders',
            name='Customer_Name',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Status',
            field=models.BooleanField(default='False'),
        ),
    ]
